apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::712123673000:user/kubectl-user
      username: kubectl-user
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::712123673000:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes