apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-dragonboat-app
  labels:
    app: capstone-dragonboat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-dragonboat-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-dragonboat-app
    spec:
      containers:
        - image: 712123673000.dkr.ecr.us-east-1.amazonaws.com/capstone-dragonboat-app
          name: capstone-dragonboat-app
          ports:
            - containerPort: 80
              name: http-server
      imagePullSecrets:
        - name: ecr-secret