apiVersion: v1
kind: Service
metadata:
  name: capstone-dragonboat-app
  labels:
    name: capstone-dragonboat-app
spec:
  selector:
    app: capstone-dragonboat-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP